from setuptools import setup

setup(
    name='npixloader',
    version='0.1.0',    
    description='NPIXLoader',
    url='https://github.com/micllynn/BehNPix_ExpLoader',
    author='Michael Lynn',
    install_requires = [
        "asttokens==3.0.0",
        "bottleneck==1.4.2",
        "colorama==0.4.6",
        "comm==0.2.2",
        "contourpy==1.3.1",
        "cycler==0.11.0",
        "debugpy==1.8.14",
        "decorator==5.2.1",
        "exceptiongroup==1.2.2",
        "executing==2.2.0",
        "fonttools==4.55.3",
        "h5py",  # installed via pip, no version info in conda list
        "importlib-metadata==8.6.1",
        "ipykernel==6.29.5",
        "ipython==9.1.0",
        "ipython_pygments_lexers==1.1.1",
        "jedi==0.19.2",
        "joblib==1.4.2",
        "jupyter_client==8.6.3",
        "jupyter_core==5.7.2",
        "kiwisolver==1.4.8",
        "mat4py",  # pip-installed, version unspecified
        "matplotlib-inline==0.1.7",
        "mkl-service==2.4.0",
        "mkl_fft==1.3.11",
        "mkl_random==1.2.8",
        "nest-asyncio==1.6.0",
        "numexpr==2.10.1",
        "numpy==2.2.4",
        "packaging==25.0",
        "pandas==2.2.3",
        "parso==0.8.4",
        "pickleshare==0.7.5",
        "pillow==11.1.0",
        "pip==25.0.1",
        "platformdirs==4.3.7",
        "prompt-toolkit==3.0.51",
        "psutil==7.0.0",
        "pure_eval==0.2.3",
        "pygments==2.19.1",
        "pymatreader",  # pip-installed, version unspecified
        "pyparsing==3.2.0",
        "python-dateutil==2.9.0.post0",
        "pytz==2024.1",
        "pywin32==307",
        "pyzmq==26.4.0",
        "scikit-learn==1.6.1",
        "scipy==1.15.2",
        "seaborn==0.13.2",
        "six==1.17.0",
        "stack_data==0.6.3",
        "threadpoolctl==3.5.0",
        "tornado==6.4.2",
        "traitlets==5.14.3",
        "typing_extensions==4.13.2",
        "wcwidth==0.2.13",
        "xmltodict",  # pip-installed
        "zetapy",     # pip-installed
        "zipp==3.21.0",
    ],
)